# NumPy Exercises 

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [3]:
import numpy as np

#### Create an array of 10 zeros 

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### Create an array of 10 fives

In [4]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### Create an array of the integers from 10 to 50

In [5]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### Create an array of all the even integers from 10 to 50

In [6]:
np.arange(10,50,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

#### Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [9]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### Use NumPy to generate a random number between 0 and 1

In [13]:
np.random.normal(0,1)

0.6336489107264223

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [17]:
np.random.normal(size=25)

array([-0.09698905,  1.80754831,  0.31297512, -0.24461396, -0.60973942,
       -0.62826971,  0.99962458, -2.37770475,  0.42270355, -0.54507921,
       -1.14509785,  0.84671334,  0.09560819, -0.17726859, -0.40802962,
       -0.41079601, -1.32587848,  0.16916885, -0.37436864,  1.03498609,
       -1.983437  ,  0.41455846,  2.27865573, -0.60377523,  0.19007666])

#### Create the following matrix:

In [21]:
np.random.random((10,10))

array([[0.25427539, 0.40446347, 0.22576629, 0.69906173, 0.88655672,
        0.80402971, 0.42589663, 0.06329804, 0.28746763, 0.2281423 ],
       [0.17165018, 0.33550189, 0.6768168 , 0.18113861, 0.74913749,
        0.31399998, 0.42026732, 0.0091819 , 0.12422844, 0.81707189],
       [0.08384457, 0.63617099, 0.34066679, 0.19796207, 0.77737973,
        0.7569188 , 0.63345388, 0.85862494, 0.44517335, 0.05898121],
       [0.17662025, 0.03870328, 0.99460647, 0.54658472, 0.79835011,
        0.27906495, 0.53565274, 0.13257244, 0.53900612, 0.95206318],
       [0.53306064, 0.78416762, 0.20512386, 0.45136898, 0.45234986,
        0.08451591, 0.4584481 , 0.27267228, 0.99829781, 0.29990656],
       [0.00112026, 0.79214156, 0.27867142, 0.40741198, 0.79888769,
        0.93644829, 0.35365145, 0.12927862, 0.1881751 , 0.09187074],
       [0.02902197, 0.50021044, 0.66745362, 0.81080189, 0.30285568,
        0.90201985, 0.62178956, 0.6444862 , 0.56651242, 0.4322582 ],
       [0.46358564, 0.83328711, 0.4880888

#### Create an array of 20 linearly spaced points between 0 and 1:

In [22]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [4]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [5]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [6]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [7]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [8]:
print(mat[3:4,4:5])

[[20]]


In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [10]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [14]:
mat[4:5]

array([[21, 22, 23, 24, 25]])

In [0]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [21]:
mat[3:5]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### Get the sum of all the values in mat

In [22]:
mat.sum()

325

#### Get the standard deviation of the values in mat

In [23]:
mat.std()

7.211102550927978

#### Get the sum of all the columns in mat

In [26]:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

#### Get the sum of all the rows in mat

In [25]:
mat.sum(axis=1)

array([ 15,  40,  65,  90, 115])

# Great Job!